### ISSUE TITLE
Remove `with` and pip interface for blocks

### ISSUE THREAD

**Issue by Roger-luo** [QuantumBFS/Yao.jl#113]
function pip `|>` cannot indicates side effects of blocks, and `with` is too complex. We should remove these two first in v0.2. And add something better when we are able to.

**Comment by GiggleLiu** [comment]
benefit of `|>`

e.g. we have a circuit of GAN, register is under the following operations

`generator circuit, add one ancilla qubit, discriminator circuit, measure`

* It is natural & cool to code like
               `reg |> generator |> addbit(1) |> discriminator |> measure`.
rather than
               `measure(apply!(addbit!(apply!(reg, generator), 1), discriminator)`.

* Register's content can change under operator is ituitive, which has no confusion. This should be a superior rule than Julia's side effect must have `!` rule.

**Comment by Roger-luo** [comment]
@GiggleLiu check this, just a proposal, inspired by [MXNet.jl](https://github.com/dmlc/MXNet.jl), the problem is to keep use `|>` as an eye sugar without implicit using its original meaning on pure functions pips, we should use a macro (which is designed to do this job):

## Demo

### Simple Chained Blocks

```julia
circuit = @chain put(1=>X) |> put(2=>X)  |> kron(X for i=1:5)  |> put(6=>phase(0.1))

apply!(reg, circuit)
mat(circuit)
```

### Nested Chained Blocks

```Julia
circuit = @chain put(1 => @chain X |> Y |> Z  ) |> @chain kron(H for i=1:5) |> put(8=>phase(0.1))

apply!(reg, circuit)
mat(circuit)
```

### Long Chained Blocks

Case 1:

```julia
circuit = @chain put(1=>X) |> put(2=>H) |> put(3=>H) |>
              kron(H for i=1:5) |> put(6=>H)

apply!(reg, circuit)
mat(circuit)
```

Case 2 (Nested)

```julia
circuit = @chain put(1=>X) |> put(2=>H) |> 
                             @chain put(1=>X) |> kron(H for i=1:5)

apply!(reg, circuit)
mat(circuit)
```

## Advantages

###  1. Better sugar with convenient explicit side-effect

The main problem of `|>` is because when `|>` is overloaded as `apply!` for blocks, this is actually different with function calls. Function calls can use function name to represent the side-effect explicitly:

```julia
A |> tweak!
```

However, since any block instance can use `|>` now, then we have 

```julia
g = kron(X for i=1:5)
reg |> g
```

And it is hard to notice (at first glance), if you do not want to tweak your original *registers* you need to write

```Julia
g = kron(X for i=1:5)
copy(reg) |> g # but why? g does not have a !
```

This could be quite misleading with the original capability of `|>`. This will reduce our code's readability as Yao is designed for humans. This could be something bad.

However, what is the different with a `@chain` and `|>`? similar with MXNet.jl, no matter what you want to do with such a chained circuit, you just want to use `|>` to chain them together with good readability, which is great.

Without `@chain`, this could be hard to implement and can be ambiguous

#### Use `|>` to construct a circuit rather than function call

The situation is, if people use `|>` as a functional

```
reg |> X |> Y
```

this works, but when you want to use the object of this circuit, you have to re-write it again with `chain` function. This is not necessary. Say if I need to call `adjoint` or `mat`, how do I get a concrete object of a long chained circuit with `|>`?

**does not look possible!**

We should use `|>` to construct a object of a circuit rather than function call. Or you will need write more code. Especially, when someone is using REPL (you don't have the object you are actually using).

#### Why it is hard to implement?

To implement this with only `|>`, you will need to define a mid-type to capture the constructor state in the runtime, let's say `ChainContainer`

```julia
import Base: |>
|>(lhs::AbstractBlock, rhs::AbstractBlock) = chain_container(lhs, rhs)
```

or you will mix up with un-expected `Chain`

```julia
import Base: |>
|>(lhs::AbstractBlock, rhs::AbstractBlock) = chain(lhs, rhs)

# this is not expected when
X |> X|> X # produce

# chain
#     chain
#         - X
#         - X
#     - X
```

To solve this problem, you have to mess up with more definition on`|>`.

similar for the original `with` and `with!` implementation, it requires a type for `Context`, this will tag a register and decide whether it will use copy, which is totally not necessary.

### 2. this keeps a very similar sugar with **function pip proposal** without ambiguous

You can use `|>` happily now, since this is in an macro, *it is safe!* and nested macros will solve the
ambiguity naturally.

```julia
@chain X |> Y |> Z # will directly call chain(X, Y, Z)
circuit = @chain put(1=>X) |> put(2=>H) |> 
                             @chain put(1=>X) |> kron(H for i=1:5)
# will call
# chain(put(1=>X), put(2=>H), chain(put(1=>X), kron(H for i=1:5)))
```

See? this macro produce better readability and less parenthesis! And it is easy to implement without any mid-types!

### 3. this is more explicit than original `with` method (but simpler):

for the original with method, print it inside `with` environment is confusing:
whether to print the `register` or the `Context`?  There will be too much noise if you print the `Context` (nobody care about this), but it would be confusing if you print the `register`.

And you need to write a `register` for twice: first to pass it to `with`, then define the callback, and callback can be dangerous.

```julia
with(regester) do r
r |> X |> Y |> Z
end
```

**Comment by GiggleLiu** [comment]
Firstly, We want something **easier** to use than `apply!(reg, block)`. At this point, `with` and `@chain` is not acceptable, they make things even more complicated.

You are basically saying all functions with **side-effect** should append `!`, without exclusion.
We all know it is **impossible**. Because if we implement `call` to a type, the name of instances are not decided by us.

My concern comes from practise, I like to use `reg |> circuit1 |> focus!(2,3,4) |> circuit2 |> relax!`, interweaving functions and circuit, functions are ended with `!`, but `circuit`s does not. We can distinguish the `intance`s and `method`s immediatedly. It is very convenient.

Register passing a circuit, it changes, there is nothing non-intuitive, A `!` is redundant.

**Comment by Roger-luo** [comment]
So, the decision is to keep `|>` for those pipe lovers, but for who cares safety, there is also an explicit `apply!`.
