### ISSUE TITLE
Support for lowering to QASM

### ISSUE THREAD

**Issue by Roger-luo** [QuantumBFS/Yao.jl#124]
# Proposal on supporting QASM

QASM is a widely used format for describing a quantum circuit or a sequence of quantum operations.
Since our block tree is a higher format of quantum circuit, to interact with other libraries (e.g import old projects into Yao, export block trees to hardware, etc.) supporting QASM will give Yao this ability.

## Related work

[openqasm](https://github.com/Qiskit/openqasm)
[scaffcc-python](https://github.com/singular-value/scaffcc-python)
[rust-QASM](https://github.com/QCGPU/qasm-rust)
[Quantum](https://github.com/Microsoft/Quantum/pull/58)

### Lowering Block Tree to QASM

The block tree have already contain complete information about a quantum circuit. Simply lowering the composite blocks to a single sequence should be easy.

### Parsing QASM back to Block Tree

*TO BE DONE*

**Comment by GiggleLiu** [comment]
Now it can be very easy to dump QASM with unified subblocks and iparameter interfaces. Let’s keep it moving.

### Remarks
QASM is the lowest level we are able to go towards hardware, unless some experts are willing to contribute codes. i.e. we are not going to support the following features in near term
* noisy circuit simulation
* quantum gate optimization
* device control (including IBM cloud)

Agree?

**Comment by Roger-luo** [comment]
XRef: https://github.com/thautwarm/RBNF.jl

**Comment by Roger-luo** [comment]
this is in [YaoQASM](https://github.com/QuantumBFS/YaoQASM.jl) now
