### ISSUE TITLE
Broadcastable Register

### ISSUE THREAD

**Issue by GiggleLiu** [QuantumBFS/Yao.jl#139]
Going to support broadcast for  batched register, something like this
```
function broadcastable(reg::DefaultRegister{B}) where B
    st = reg |> rank3
    Tuple(register(view(st, :, :, i)) for i = 1:B)
end
broadcastable(reg::DefaultRegister{1}) = Ref{reg}

@testset "broadcast register" begin
    reg = rand_state(5,3)
    c = put(5, 2=>X)
    ra = copy(reg)
    rb = copy(reg)
    @test all(ra .|> Ref(c) .≈ rb .|> Ref(c))
    @test typeof.(reg)[1] <: DefaultRegister{<:Any, <:Any, <:SubArray}
end
```
This realization requrires modifications of intrinsic functions (not shown here).

Any comments?

**Comment by Roger-luo** [comment]
why not just let register support broadcast?

**Comment by GiggleLiu** [comment]
`broadcastable` is the broadcast interface. Do you mean implement `broadcast` directly? what's the advantage of doing this?

**Comment by Roger-luo** [comment]
directly inherit broadcast will not cause an extra API.

**Comment by Roger-luo** [comment]
We don't want to create so much API, or this will be too noisy and not Julian. Julia types are duck typed, if you implement broadcast then it is broadcast-able, you don't need to create an API for this.

**Comment by GiggleLiu** [comment]
`broadcastable` is the offically recommended interface. https://github.com/JuliaLang/julia/pull/26435

**Comment by Roger-luo** [comment]
I see. But shouldn't we should provide the batch as multi-process/multi-threaded? rather than a Tuple. Or what's the meaning of a batch.

**Comment by Roger-luo** [comment]
> Generator seems better than Tuple for a single threading task.

To return a generator:

```julia
function broadcastable(reg::DefaultRegister{B}) where B
    st = reg |> rank3
    (register(view(st, :, :, i)) for i = 1:B)
end
```

But what do you mean for single threaded? better performance?

I would prefer `process` rather than `threading` for batch on CPUs, because usually each single task in a batch can take a long time, use process is easier to dispatch on multiple CPUs.

**Comment by GiggleLiu** [comment]
Cool, thanks for your suggestion.
Batch wise operations should not use multiple processing, we don’t want data communication. This is the same as matrix operations.

rank3 is the (active, remaining, batch) tensor representation for reg. I can not find a better name.

**Comment by Roger-luo** [comment]
They call it `cube` in `Eigen` and some other libs.
