### ISSUE TITLE
Refactor parameter and dispatch! interfaces

### ISSUE THREAD

**Issue by GiggleLiu** [QuantumBFS/Yao.jl#140]
`AbstractBlock` interface now requires
* `subblocks` (renamed from `blocks`)

Make the parameter system clear, use `iparameters`  for intrinsic (parameters in subblocks are not included) parameters and `parameters` for total parameters.

A intrinsic parametric block should implement
* `iparameters`: intrinsic parameters,
* `niparameters`: number of intrinsic parameters,
* `setiparameters!`: set intrinsic parameters.
Otherwise, `niparameters` is `0`.

In this way, `parameters`, `nparameters` and `dispatch!` can have simple and uniform interface.

```
"""
    nparameters(c::AbstractBlock) -> Int

number of parameters, including parameters in sublocks.
"""
function nparameters(c::AbstractBlock)
    count = niparameters(c)
    for each in subblocks(c)
        count += nparameters(each)
    end
    count
end

"""
    parameters(c::AbstractBlock, output=Float64[]) -> Vector

get all parameters including sublocks.
"""
function parameters(c::AbstractBlock, output=Float64[])
    append!(output, iparameters(c))
    for blk in subblocks(c)
        append!(output, parameters(blk))
    end
    output
end

function dispatch!!(func::Function, r::AbstractBlock, params)
    setiparameters!(func, r, (popfirst!(params) for i=1:niparameters(r)))
    for blk in subblocks(r)
        dispatch!!(func, blk, params)
    end
    r
end
dispatch!(func::Function, r::AbstractBlock, params) = dispatch!!(func, r, params |> copy)
```

**Comment by Roger-luo** [comment]
What's `dispatch!!`? we don't need to create a new API.

**Comment by GiggleLiu** [comment]
dispatch!! is easier to implement, but it will pop out the vector/set. To make API compatible, we need to rename it to dispatch!! to show it has two side effects.

**Comment by GiggleLiu** [comment]
When subtyping new blocks, iparameters is easier and clearer than parameters.

Imaging subtyping a chain like block, you have to iterate over subblocks to get parameters. But it can be automatically done since you have subblocks as the standard API for tree.

I don not think implementing dispatch!, parameters, cache and autodiff case by case is a clever solution.

**Comment by Roger-luo** [comment]
I still don't understand, what's the difference? can you demonstrate what is a `iparameter`?

**Comment by GiggleLiu** [comment]
> I still don't understand, what's the difference? can you demonstrate what is a `iparameter`?

It is clear enough in the issue, we “use `iparameters`  for intrinsic (parameters in subblocks are not included) parameters”.  e.g.
For chain, iparameters returns (), for  RotationBlock, it returns (theta,). Every detail is in the code, feel free to find out more examples.

> And I don't think this should be in **v0.3** until we make this clear.

Refactoring is decided, details can be discussed.

> What is this related to this topic? What do you mean case by case?

Quite obvious if you see the above dispatch!! function. The master branch contains old realization, one need to write dispatch! for composite, primitive , tagblock and sequence, and this realization is based on the assumption that a composite block/tag block does contain intrinsic parameters.

> Current `blocks` returns an iterator, therefore, simply apply `parameters` to the iterator will return > ANY block's parameters. What's the difference between your new `iparameters`?

Current blocks interface is only for composite blocks. The difference between iparameters and parameters is answered above.

> `parameters` can be set to `Tuple{}` by default, you don't need to implement this method if you don't have any parameters.

Not true for a composite block or a tag block.

> BTW, you don't say silly, this is not a good way to reply issues publicly.

Thanks, but please focus on the issue. Please read the code carefully and ask more constructive questions, so that we can make this discussion fruitful.

**Comment by Roger-luo** [comment]
> For chain, iparameters returns (), for RotationBlock, it returns (theta,). Every detail is in the code, feel free to find out more examples.

Then it is the same with `parameters`, why not just use `parameters`?

It would better if you open a separated PR for refactoring `dispatch!` and `parameters`, I can't read a large PR with mixed implementation.

**Comment by GiggleLiu** [comment]
parameters for chain returns concatenation of parameters from subblocks. It counts recursive.

**Comment by GiggleLiu** [comment]
cloed by #138
