### ISSUE TITLE
Clarification of Swap, SWAP and swap

### ISSUE THREAD

**Issue by congzlwag** [QuantumBFS/Yao.jl#163]
It took me a few days to figure it out that:
Swap is a union of types like Swap{2,Complex{Float64}}, SWAP is a gate whose type is another type: SWAPGate{Complex{Float64}}, while swap is a function constructing an instance of the Swap{...} type.

Their similar names are sort of confusing, while the functionality that users need is simple, I hope they (construction with swap, or directly usage of SWAP) could be integrated. At least they can mention each other in their own documentation, clarify their difference in usage and comparing the pros and cons.

It would also be better to offer some minimal examples in the docs, like for SWAP:

```julia
julia> r = register(bit"010")
DefaultRegister{1, Array{Complex{Float64},2}}
    active qubits: 3/3

julia> apply!(r, put(3,(2,3)=>SWAP))
DefaultRegister{1, Array{Complex{Float64},2}}
    active qubits: 3/3

julia> r.state
8×1 Array{Complex{Float64},2}:
 0.0 + 0.0im
 0.0 + 0.0im
 0.0 + 0.0im
 0.0 + 0.0im
 1.0 + 0.0im
 0.0 + 0.0im
 0.0 + 0.0im
 0.0 + 0.0im

```

**Comment by GiggleLiu** [comment]
Indead, it is a problem.

Do you think moving all rare/confusing constant gate to a submodule would solve your problem? like Const.SWAP and Const.CNOT. It will also help people putting more useful constant gates like sqrt(X) into Yao.jl without ruining the naming environment.

And the document is always a problem. Roger now is trying hard to write a more detailed one in the release 0.4. Your suggestions are valuable.

**Comment by Roger-luo** [comment]
SWAP is in `ConstGate` module now.
