### ISSUE TITLE
Benchmark images link broken.

### ISSUE THREAD

**Issue by we-taper** [QuantumBFS/Yao.jl#164]
The images for the benchmark are broken.
 (<https://quantumbfs.github.io/Yao.jl/stable/dev/benchmark/>)

**Comment by GiggleLiu** [comment]
Hmm, this is strange. Roger will try to fix this issue in the next release :smile: 

For someone who want to see the benchmark, please check `*.png` files under this folder
https://github.com/QuantumBFS/Yao.jl/tree/master/docs/src/assets/benchmarks

**Comment by GiggleLiu** [comment]
@Roger-luo 
Now, we need a new benchmark for v0.4.
