### ISSUE TITLE
`mat` does not error when the number of qubits is too large 

### ISSUE THREAD

**Issue by Roger-luo** [QuantumBFS/Yao.jl#166]
MWE:

```julia
julia> put(100, 1=>X) |> mat
0×0 LuxurySparse.PermMatrix{Complex{Float64},Int64,Array{Complex{Float64},1},Array{Int64,1}}
```

Should be solved by traits in 0.4.

**Comment by Roger-luo** [comment]
Since we decided not to have matrix traits, but to make all the blocks to have matrix, this bug is back. It probably can be solved by adding a check to each routines that generates the matrix.

**Comment by GiggleLiu** [comment]
> adding a check to each routines

you mean add a check for every `mat` function?

**Comment by Roger-luo** [comment]
Routines like unmat etc.

**Comment by GiggleLiu** [comment]
I think, we should probably fix it in the `PermMatrix` level? Is this behavior same for dense arrays?

**Comment by Roger-luo** [comment]
No it's just because some routines didn't check the proposed size. And the location integer just overflow then you get an empty matrix. You can't solve this from LuxurySparse. The constrictor knows nothing about the potential overflow.

**Comment by GiggleLiu** [comment]
I would suggest not considering it as a bug
```
julia> randn(2<<100)
0-element Array{Float64,1}
```

Program should not be blamed for stupid errors made by human beings.

**Comment by Roger-luo** [comment]
It's OK for << to overflow, that's its definition and it's explicit enough. We don't have any explicit expression here, which make it not intuitive. It's apparently hard to guess this is because integer overflow.

**Comment by GiggleLiu** [comment]
Trying to get a matrix of size `1<<100` is already very strange. Any using case?

**Comment by Roger-luo** [comment]
The point is unless you input 1<<100, or we should throw an error.

**Comment by Roger-luo** [comment]
It's not about anything else but correctness.

**Comment by GiggleLiu** [comment]
Agree if it does not increase a lot of codes.
