### ISSUE TITLE
Wrong highlight in documents & how to fix it

### ISSUE THREAD

**Issue by zhaouv** [QuantumBFS/Yao.jl#171]
for example https://quantumbfs.github.io/Yao.jl/stable/tutorial/Grover/  
it is regarded as php  
![image](https://user-images.githubusercontent.com/26158289/55579825-2930aa00-56e7-11e9-98e0-6df0fcfb88c7.png)
you can fix it by inserting `hljs.configure({languages:['julia']})` before https://github.com/JuliaDocs/Documenter.jl/blob/master/assets/html/documenter.js#L58

here it the result  
![image](https://user-images.githubusercontent.com/26158289/55580278-369a6400-56e8-11e9-9405-92b4a61a3414.png)

and the question becomes how to change the file **documenter.js**.  
it seems that **Documenter.jl** has not provided this API.

so, you have to change it manually here https://github.com/QuantumBFS/Yao.jl/blob/master/.travis.yml

or send an issue to **Documenter.jl**

**Comment by Roger-luo** [comment]
Good catch. That's quite strange!

I'm updating Documenter to latest version and fix make script, let's if this fix this problem. If this doesn't work I think there's should be something wrong in upstream.

**Comment by Roger-luo** [comment]
However, it seems fine on my laptop:

![image](https://user-images.githubusercontent.com/8445510/55581157-bb1fcd80-574e-11e9-9d43-dfd0b59a3327.png)

**Comment by zhaouv** [comment]
only in some blocks

**Comment by Roger-luo** [comment]
I think this is not our issue and should be fixed in next Documenter release.
