### ISSUE TITLE
Should the sequence of location matter when put ChainBlocks? 

### ISSUE THREAD

**Issue by frankwswang** [QuantumBFS/Yao.jl#173]
Today I was testing the `put` function with the below method:
`C2 = put(N, Tuple(m:n,)=>C1)`
where `C1` is a ChainBlock, `n>m`.

I found that with `Tuple(m:n,)` and `Tuple(n:-1:m,)` I got different outputs.

Here is an example:

```
julia> c1 = chain(3, put(3, 1=>X), put(3, 2=>X))
Total: 3, DataType: Complex{Float64}
chain
├─ put on (1)
│  └─ X gate
└─ put on (2)
   └─ X gate


julia> c2 = put(5, Tuple(3:5,)=>c1)
Total: 5, DataType: Complex{Float64}
put on (3, 4, 5)
└─ chain
   ├─ put on (1)
   │  └─ X gate
   └─ put on (2)
      └─ X gate


julia> c3 = put(5, Tuple(5:-1:3,)=>c1)
Total: 5, DataType: Complex{Float64}
put on (5, 4, 3)
└─ chain
   ├─ put on (1)
   │  └─ X gate
   └─ put on (2)
      └─ X gate


julia> reg1=register(bit"00001")
DefaultRegister{1, Array{Complex{Float64},2}}
    active qubits: 5/5

julia> measure(copy(reg1) |> c2)
1-element Array{Int64,1}:
 13

julia> measure(copy(reg1) |> c3)
1-element Array{Int64,1}:
 25
```
Clearly only `C3` outputs the right answer if we assume the qubit sequence from lower order to a higher order(down->up, low->high) is global for the entire circuit. I wonder if this is designed by purpose, but I think it's probably better if we can make the `put` function not sensitive to the sequence of the location range to avoid potential mistakes in coding.

Just a suggestion, thank you!

**Comment by GiggleLiu** [comment]
> I found that with `Tuple(m:n,)` and `Tuple(n:-1:m,)` I got different outputs.

This is expected. The locations in a tuple specifies the ordering of qubits in that subspace. If we make it non-sensitive to ordering, we are not possible to let `put(n, (1,3)=>CNOT)` represent 1 control 3 while `put(n, (3, 1)=>CNOT)` represent 3 control 1. This is why `put(n, 2:3=>CNOT)` can be confusing and is forbidden in `Yao.jl`.

BTW: if you have a large sub-block, we would suggest using `concentrate(n, put(10, 1=>X), 2:11)`. This avoids constructing sub-blocks matrices explicitly and accelerates simulation.

Thanks for asking and giving us a chance to clarify.

**Comment by frankwswang** [comment]
Understood. However, if the only application for this location sensitivity of `put` is applying `CNOT` gate, I think it's better to just add a specific method for CNOT instead of keeping the sensitivity not only because for avoiding mistakes for other situations but also because to decide which line to be controlled should be the property of `CNOT` not the `put` function. 

I suggest adding this method to `CNOT`:
```
CNOT(1:3)
``` 
where the first parameter is the control location, the second parameter is the gate location.

So that we can write:
```
put(n, 1:3=>CNOT(1,3))
```

As for `put` function we can have only two methods for location part: 

```
put(N, i=>GATE)
put(N, m:n=>ChainBlock)
```

**Comment by GiggleLiu** [comment]
There is an eye candy `cnot` in Yao.jl.

Thanks for your suggestion, but one should notice `put(10, (2,7)=>CNOT)` is also very useful.

**Comment by Roger-luo** [comment]
I agree with @frankwswang , there is no ambiguity between `1:3` and tuples, we should allow one to use `UnitRange` and `StepRange`, it's more convenient sometimes, since there completely no need to convert things to tuple every time you have a block on contiguous locations.

But the described behaviour is a feature, since we should allow one to change the wire location of a block.

**Comment by GiggleLiu** [comment]
The sub-block in `put` should be short for performance. Allowing `put(nbit, m:n=>block)` is encouraging the inefficient simulation. Use `Concentrate` for fitting a subprogram into a circuit.

**Comment by GiggleLiu** [comment]
I don't prefer introducing additional interfaces when it is not necessary. It will increase the maintenance pressure.

Eye candies are cheap, users are clever, they can define one for themselves.

**Comment by Roger-luo** [comment]
If `put` means to use on single qubit gates, we should provide an error when multiple qubit gate is feeded.

Or there's nothing to do with encouraging to use `concentrate`, it is too vague about what is encouraged by preventing one from using the sugar.

**Comment by GiggleLiu** [comment]
> it makes the code `drier`

DRY means don't repeat yourself. More interface with similar functionality, more codes to maintain, which means not DRY.

**Comment by Roger-luo** [comment]
It makes the users' code drier. you have stand here as a package provider not a user. If this logic holds we shouldn't have things like comprehension at all in Julia `[k for k in 1:2]`, one should use `hcat` and `vcat`, since supporting comprehension is an extra interface and require a lot more work, it make things hard to maintain.

But why we are having comprehension and are happy with it? It's because it make the users' code drier. you can input less things while doing the same job.

**Comment by Roger-luo** [comment]
I think the original question is solved we could open other issues for further discussion.
