### ISSUE TITLE
Compatibility issues

### ISSUE THREAD

**Issue by GiggleLiu** [QuantumBFS/Yao.jl#176]
* [x] `matrixgate` has no deprecation warning.
* [x] fix the following error
```julia
julia> using Yao

julia> a = put(3, 2=>Rx(0.3))
nqubits: 3, datatype: Complex{Float64}
put on (2)
└─ rot(X gate, 0.3)

julia> dispatch!(a, 0.3)
ERROR: StackOverflowError:
Stacktrace:
 [1] setiparams!(::PutBlock{3,1,1,Complex{Float64},RotationGate{1,Float64,XGate{Complex{Float64}}}}, ::Float64) at /home/leo/.julia/dev/YaoBlocks/src/abstract_block.jl:132 (repeats 8120 times)
 [2] setiparams! at /home/leo/.julia/dev/YaoBlocks/src/abstract_block.jl:140 [inlined]
 [3] dispatch!(::Function, ::PutBlock{3,1,1,Complex{Float64},RotationGate{1,Float64,XGate{Complex{Float64}}}}, ::Float64) at /home/leo/.julia/dev/YaoBlocks/src/abstract_block.jl:206
 [4] dispatch!(::PutBlock{3,1,1,Complex{Float64},RotationGate{1,Float64,XGate{Complex{Float64}}}}, ::Float64) at /home/leo/.julia/dev/YaoBlocks/src/abstract_block.jl:222
 [5] top-level scope at none:0
```

* [x] `block(blk)` should have deprecation warning.
* [x] put the deprecation plan of `DefaultRegister`, `MatrixBlock` in to release note, alias `DefaultRegister` to `ArrayReg`, `MatrixBlock` to `AbstractBlock`.

* [x] This behavior is not consistent.
```julia
julia> Rx(0)
rot(X gate, 0.0)

julia> shift(0)
ERROR: MethodError: no method matching shift(::Int64)
Closest candidates are:
  shift(::AbstractFloat) at /home/leo/.julia/dev/YaoBlocks/src/primitive/shift_gate.jl:19
Stacktrace:
 [1] top-level scope at none:0
```
* [x] add`timeevolve` interface
* [x] depwarn `collect`
* [x] depwarn `join`

* [x] Fix following operations
```julia
julia> reg = rand_state(3)
ArrayReg{1, Complex{Float64}, Array...}
    active qubits: 3/3

julia> reg'*reg
0.6281466772067442 + 0.020640460232378074im
```

Notice:
```julia
julia> using LinearAlgebra

julia> LinearAlgebra.dot([im], [im])
1 + 0im
```

And some native code should also be fixed, `AdjointReg` and `ArrayReg` should not be compared

```julia
for op in [:(==), :≈]
    @eval function Base.$op(lhs::ArrayRegOrAdjointArrayReg{B}, rhs::ArrayRegOrAdjointArrayReg{B}) where B
        ($op)(state(lhs), state(rhs))
    end
end
```

Remove this line.
```julia
Base.:*(op::AbstractMatrix, r::ArrayRegOrAdjointArrayReg) = op * state(r)
```

And this one is wrong for `AdjointReg`.
```julia
Base.:-(reg::ArrayRegOrAdjointArrayReg) = ArrayReg(-state(reg))
```

When changing/adding new features. Please submit pull request, so that I can review these changes to prevent these naive codes.  To find this error, I spent a lot of time, so please add more tests. Especially for `AdjointReg`, untested features should be removed immediately.

- [x] add deprecation warning for `indices_with`
- [ ] add deprecation of `FunctionBlock` to release note.
- [x] `TimeEvolution` should be able to accept complex numbers.
- [ ] it is not good to bind a function to an attribute
```
@interface content(x::AbstractContainer) = x.content
```

- [x] QFT example is not working, don't know why
```julia
CRk(i::Int, j::Int, k::Int) = control([i, ], j=>shift(2π/(1<<k)))
CRot(n::Int, i::Int) = chain(i==j ? kron(i=>H) : CRk(j, i, j-i+1) for j = i:n)
QFTCircuit(n::Int) = chain(n, CRot(n, i) for i = 1:n)
```

**Comment by Roger-luo** [comment]
`dispatch!` is a bug I found the other day, it should be fixed once I tag each component package.

**Comment by Roger-luo** [comment]
@GiggleLiu 

> it is not good to bind a function to an attribute

This is exactly what `block` was, we don't encourage people to use dot to get properties here in general since v0.6.
