### ISSUE TITLE
Discussion of Variable Scope for `Register`

### ISSUE THREAD

**Issue by frankwswang** [QuantumBFS/Yao.jl#180]
I noticed that the scope of a `register` in Yao is not local, which means that alternating `reg1` in a local scope can change the value of a `register` with the same name in its parent scope:
```
using Yao, Yao.Blocks
function test(n)          
    reg2 = product_state(n,5)
    println("0 $(measure(reg2))")       
    for i=1:n
        reg2 = zero_state(n)
        println("1 $(measure(reg2))")                  
        reg2 |> put(i,i=>X)
        println("2 $(measure(reg2))")        
    end                        
    println("3 $(measure(reg2))")
    reg2
end 
```
The result is:
```
julia> test(3)
0 [5]
1 [0]
2 [1]
1 [0]
2 [2]
1 [0]
2 [4]
3 [4]
DefaultRegister{1, Array{Complex{Float64},2}}
    active qubits: 3/3
```
If this is designed as expect, then I assume the name of a `register` is actually the pointer points at its memory address. If this is correct, I suggest stressing this property in the documentation.

Secondly, I also noticed that even a `register` is a "global" variable, it still follows the local-scope definition of Julia, which means if I remove defining `reg2` in the top-level of the function `test`:
```
function test(n)          
    #reg2 = product_state(n,5)
    println("0 $(measure(reg2))")       
    for i=1:n
        reg2 = zero_state(n)
        println("1 $(measure(reg2))")                  
        reg2 |> put(i,i=>X)
        println("2 $(measure(reg2))")        
    end                        
    println("3 $(measure(reg2))")
    reg2
end 
```
I get this error:
```
julia> test(3)
ERROR: UndefVarError: reg2 not defined
```
It shows that for Julia `reg2` is still only accessible inside the `for` loop. I wonder if this is also desined as expect since `reg2` won't have any diferent `register` with same name inside function `test`. Thank you!

**Comment by Roger-luo** [comment]
I don't get it. This is just a normal Julia variable behaviour.

**Comment by frankwswang** [comment]
I thought it is Yao's behavior, then I realized it is Julia's feature, Sorry! Now my only confuse is that why inside a `function`, Changing the value of a variable inside the `for` loop will affect the variable with the same name outside the `for` loop:
```
function forf()
    n = 0
    for i=1:10
        # local n = 1
        local n = abs(-3) 
        # n = i + 1
    end
    n
end

julia> forf()
0 
```
While without using a `function`, the variable inside the `for` loop behaves as local variable:
```
 julia> m = 0
0

julia> for i=1:10
           m =i+1
           end

julia> m
0  
```
This question is irrelevant to Yao, I apologize for it.

**Comment by Roger-luo** [comment]
This is because global scope is different from local scope. But this is something going to be fixed in the future without breaking: https://github.com/JuliaLang/julia/issues/28789

FYI (Chinese): https://discourse.juliacn.com/t/topic/159
Docs: https://docs.julialang.org/en/v1/manual/variables-and-scoping/#Global-Scope-1
