### ISSUE TITLE
Links not working in examples/README.md

### ISSUE THREAD

**Issue by narendrakpatel** [QuantumBFS/Yao.jl#181]
The links in the `examples/README.md` are not working.
Current:
(https://quantumbfs.github.io/Yao.jl/latest/tutorial/GHZ/)

Expected:
(https://quantumbfs.github.io/Yao.jl/latest/examples/GHZ/)

Also, in the `/latest` version of docs, **Grover Search and Quantum Inference** example is missing.

**Comment by Roger-luo** [comment]
Grover was removed for further polish, I'll bring it back later (#175) , if you want to read the old examples, check it here: https://quantumbfs.github.io/Yao.jl/v0.3/tutorial/Grover/

examples are not supposed to be there, sorry for the confusion, they are all in current docs now with [Weave](https://github.com/mpastell/Weave.jl) files, you can also generate whichever format you prefer with Weave yourself.
