### ISSUE TITLE
Should we add a new method to support Block arrays for `dispatch!` 

### ISSUE THREAD

**Issue by frankwswang** [QuantumBFS/Yao.jl#185]
Before the function `collect(ChainBlocks)` returned a `sequences` so that we could do operations like:
```
dGates = collect(AbstractDiff, circuit)
dispatch!(+, dGates, grads.*learningRate)
```
where `grads` is an array of real number.

However, since now `collect`(`collect_blocks`) only returns an array of blocks and `disptach!` does not support the method of `dispatch!(::typeof(+), ::Array{AbstractDiff,1}, ::Array{Float64,1})` in which the 2nd parameter is an `array`, we have  to use `for` loop to achieve the purpose, which is inefficient.

I hope maybe we could add the method to support array operations. Thank you!

**Comment by Roger-luo** [comment]
I just realize this just work out of box, so actually we don't need to define any extra interface at all!

```

**Comment by Roger-luo** [comment]
I think this is solved now with a bug fix https://github.com/QuantumBFS/YaoBlocks.jl/pull/33
