### ISSUE TITLE
Measure should take rng::AbstractRng as first argument

### ISSUE THREAD

**Issue by zenna** [QuantumBFS/Yao.jl#194]
I haven't looked at internals, but I imagine measure is making some call to `rand()`.  It would be useful for it to take an `rng` as the first argument and instead call `rand(rng)`

**Comment by Roger-luo** [comment]
It is defined here, we are currently using the `sample` from `StatsBase` and yes, it is a good idea to expose this API here, it is quite straight forward actually. 

https://github.com/QuantumBFS/YaoArrayRegister.jl/blob/7a3cf82819f769faad244c72ca5b077741b2671e/src/measure.jl#L9

**Comment by Roger-luo** [comment]
the new interface is added for measure now.
