### ISSUE TITLE
Proposal for the documentation

### ISSUE THREAD

**Issue by ironmanaudi** [QuantumBFS/Yao.jl#198]
I suppose it's a good idea to attach the source code link in the correponding methods being illustrated in the docmentation, then it would be really convinient for the user to click, read and then costomize their own codes., rather than finding the corresponding src codes manaully.

**Comment by Roger-luo** [comment]
Every docstring has its corresponding link, why you think so?

**Comment by Roger-luo** [comment]
Oh, sorry, I notice some of the link is missing and the existing ones are wrong, but this is not what we maintain, so I'll just report this in upstream. Closed.
