### ISSUE TITLE
v0.6 release

### ISSUE THREAD

**Issue by Roger-luo** [QuantumBFS/Yao.jl#199]
I think for next release it can include the following new components

- [x] new website: I just bought the domain: yaoquantum.org, and we do need a front page to separate tutorials and docs
- [ ] QuDiffEq: JSoC2019, should be good to go (need tag)
- [x] YaoSym (depends on whether we finish this in time)
- [x] YaoBlocks.AD: builtin classical automatic differentiaion engine.
- [x] add `CITATION.bib` and paper to this repo
- [x] add contribution guide to homepage
- [x] name changes (#215 )
---
- [ ] YaoExtensions: need some revision and docs
- [ ] ~QuAlgorithmZoo: cleaned up, with better documentations.~

**Comment by GiggleLiu** [comment]
Haha, we are going to have a domain name! 🎉

**Comment by Roger-luo** [comment]
I'll tag a patch version later for the citation.

@JuliaRegistrator register

**Comment by Roger-luo** [comment]
@JuliaRegistrator register

**Comment by Roger-luo** [comment]
with citation

@JuliaRegistrator register

**Comment by Roger-luo** [comment]
@JuliaRegistrator register

**Comment by Roger-luo** [comment]
@JuliaRegistrator register
