### ISSUE TITLE
[RFC] resetto! or collapseto!

### ISSUE THREAD

**Issue by GiggleLiu** [QuantumBFS/Yao.jl#203]
Old API `reset!` is deprecated to `collapseto!`
https://github.com/QuantumBFS/Yao.jl/blob/e60f49a31f945c87052a4935f91052f88f9146b7/src/deprecations.jl#L11

It is still not clear if `resetto!` can be a better name for setting a qubit to specific value (experimentally equivalent to classical feedback control).

**Comment by Roger-luo** [comment]
So I think we all agree to use `resetto!` now

**Comment by GiggleLiu** [comment]
The latest design is adding a `postprocess` argument. Which can be `NoPostProcess()`, `ResetTo(bit"0011")` or `RemoveMeasure()`.

It makes the dispatch much easier. It makes a simpler design of `Measure` block with less fields possible.
