### ISSUE TITLE
Upcoming naming and convension changes for Yao v0.6.0

### ISSUE THREAD

**Issue by GiggleLiu** [QuantumBFS/Yao.jl#215]
- [x] key word argument `collapseto => resetto!` in `Measure` block and `measure` functions
- [x] prettify printing some composite blocks
    - [ ] ~`[cached] ...` => `[?] ...`~
    - [ ] ~`chain ...` => ? `...`~
    - [x] `concentrate` => `subroutine` (https://github.com/QuantumBFS/YaoBlocks.jl/pull/96)
- [x] prettify printing for constant gates, e.g. `X gate` -> `X` (https://github.com/QuantumBFS/YaoBlocks.jl/commit/489d57ab210418002092762d9d1b1edc39275bf7)

Pls feel free to discuss.

**Comment by wangleiphy** [comment]
concentrate => subroutine

**Comment by Roger-luo** [comment]
I pro `subroutine` it shorter and make more sense
