### ISSUE TITLE
Unreachable reached

### ISSUE THREAD

**Issue by Roger-luo** [QuantumBFS/Yao.jl#218]
might be a bug in 1.3, need to check it. The following code will currently crash

```julia
using Yao
r = rand_state(4)
measure!(r, nshots=3)
```

**Comment by wangleiphy** [comment]
I also had this problem. 
FYI, `measure(r, nshots=3)` works.

**Comment by GiggleLiu** [comment]
`measure!(r, nshots=3)` is not supposed to work, it collases the wavefunction directly. We should forbit it.

**Comment by Roger-luo** [comment]
yes, that's what I meant. But this seems to hit a bug as well, it is not the correct error

**Comment by Roger-luo** [comment]
Seems also causing stackoverflow here? @GiggleLiu 

https://github.com/QuantumBFS/YaoBlocks.jl/pull/92

**Comment by GiggleLiu** [comment]
fixed by https://github.com/QuantumBFS/YaoBlocks.jl/pull/100
