### ISSUE TITLE
Is there any encapsulation for Identity Gate?

### ISSUE THREAD

**Issue by Neuromancer43** [QuantumBFS/Yao.jl#250]
I need some thing like `(I+X)*(I+Z)`....
So I must use `Rz(4\pi)` or expand the formula by hand?

**Comment by Neuromancer43** [comment]
Maybe this feature is a little trivial, but it can be useful when encoding complex Hamiltonian.

**Comment by GiggleLiu** [comment]
I2 is what you want, I will conflict with LinearAngebra, so we use another name.

**Comment by Neuromancer43** [comment]
Thanks, got it.
