### ISSUE TITLE
how should i set cache_key for type ::GeneralMatrixBlock{4,4,Complex{Float64},Array{Complex{Float64},2}}

### ISSUE THREAD

**Issue by helloinrm** [QuantumBFS/Yao.jl#259]
hey,
i am using a chain consists of a list of `matblocks`. i want to cache the chain for frequent use, however the error comes out as

```
ERROR: MethodError: no method matching cache_key(::GeneralMatrixBlock{4,4,Complex{Float64},Array{Complex{Float64},2}}).
```

so how should i set the `cache_key` for it?
Thank you!

**Comment by Roger-luo** [comment]
Hi, the `cache` feature is mainly used for parameterized gates e.g `shift`, `rot` so their matrix won't be generated twice. There is no benefit of caching a `matblock` since you will be using the matrix you created anyway, thus there is no `cache_key` defined for it.

**Comment by GiggleLiu** [comment]
It looks like the chain is calling `cache_key` recursively. Might be better to define one for `matblock` too?

**Comment by Roger-luo** [comment]
OK, I think maybe just use `hash` as cache_key for matrix block makes the most sense in this case.

**Comment by helloinrm** [comment]
thanks~
