### ISSUE TITLE
How to use select! function to select a specific subspace

### ISSUE THREAD

**Issue by hjayst** [QuantumBFS/Yao.jl#260]
I got confused about the select! function in the document. As the state like $|0\rangle |psi\rangle + |1\rangle |phi\rangle$ and just ignore the normalization factor,  I measure the first qubit and only keep the state when the first qubit is measured 0 to obtain $|psi\rangle$. How to realize this by using the function select!?

**Comment by GiggleLiu** [comment]
Since `select!` operations on the whole space. You can do not the following

```julia
julia> reg = rand_state(10)
ArrayReg{1, Complex{Float64}, Array...}
    active qubits: 10/10

julia> reg_first = reg |> focus!(1)       # make the first qubit the system
ArrayReg{1, Complex{Float64}, Array...}
    active qubits: 1/10

julia> select!(reg_first, bit"0")             # project to state 0
ArrayReg{1, Complex{Float64}, Array...}
    active qubits: 0/9

julia> reg_first |> relax!                      # see the whole space
ArrayReg{1, Complex{Float64}, Array...}
    active qubits: 9/9
```

**Comment by Roger-luo** [comment]
I'm going to close this, but feel free to open a new one if you have other questions.
