### ISSUE TITLE
switch to github action

### ISSUE THREAD

**Issue by Roger-luo** [QuantumBFS/Yao.jl#261]
since travis is not supporting public repos at least for now, I think we will be transferring to github actions for all the repos under this org.

**Comment by GiggleLiu** [comment]
> travis is not supporting public repos at least for now

Do you mean private?

**Comment by Roger-luo** [comment]
no travis changes it policy recently, I think we are affected.

**Comment by GiggleLiu** [comment]
Sure, let me check if there are some bots for this. There are so many packages...
