### ISSUE TITLE
"Basic" not defined (from tutorial)

### ISSUE THREAD

**Issue by basernapairs** [QuantumBFS/Yao.jl#265]
I found this error at **mat(sym_cphase(4,2,1))** (minute 3:53) by following this tutorial ⤵
https://asciinema.org/a/HaDO421J58cmKhIBbVPhJHIr7?speed=2

![image](https://user-images.githubusercontent.com/75351310/103122493-6f981a80-46bb-11eb-9c5c-24cb979c2906.png)

![image](https://user-images.githubusercontent.com/75351310/103122342-c05b4380-46ba-11eb-9e5b-a006c670f85e.png)

**Comment by GiggleLiu** [comment]
Thanks for the issue, this clip needs to be updated.
One needs to import SymEngine explicitly to use the symbolic features.

```julia
using SymEngine
```

**Comment by basernapairs** [comment]
Got new one (error) after added SymEngine Pkg (at 03:40),

![image](https://user-images.githubusercontent.com/75351310/103128808-b264ed00-46d1-11eb-99d1-47de9c7f4e81.png)
![image](https://user-images.githubusercontent.com/75351310/103128924-f0621100-46d1-11eb-89de-8161b416791a.png)

 but the result it's fine (at 03:53)

![image](https://user-images.githubusercontent.com/75351310/103129046-5189e480-46d2-11eb-84c8-9f079053d8ee.png)

**Comment by Roger-luo** [comment]
@basernapairs you can't use a number as symbols, please refer to `SymEngine` README: https://github.com/symengine/SymEngine.jl#working-with-scalar-variables 

> Thanks for the issue, this clip needs to be updated.

@GiggleLiu have we updated the GIF?

**Comment by Roger-luo** [comment]
bump @GiggleLiu can you update that GIF if it's not then we can close this issue?

**Comment by GiggleLiu** [comment]
The clip has been updated, please check the updated tutorial: https://tutorials.yaoquantum.org/dev/
