### ISSUE TITLE
qft_circuit not defined (from tutorial)

### ISSUE THREAD

**Issue by basernapairs** [QuantumBFS/Yao.jl#267]
Hiii **qft_circuit** not defined that's it (at 05:16)
https://asciinema.org/a/HaDO421J58cmKhIBbVPhJHIr7?speed=2

![image](https://user-images.githubusercontent.com/75351310/103201710-83e24e80-492b-11eb-8bb1-adf44f707c71.png)

![image](https://user-images.githubusercontent.com/75351310/103201742-9ceaff80-492b-11eb-9077-f171af8a911a.png)

**Comment by Roger-luo** [comment]
I think `qft_circuit` is in `YaoExtensions` as demonstrated at the beginning of this animate did you add this package?

**Comment by basernapairs** [comment]
i didn't missing *YaoExtensions*

![image](https://user-images.githubusercontent.com/75351310/103322259-6bcc1580-4a78-11eb-85c9-c69d006d123a.png)

**Comment by Roger-luo** [comment]
Hi in your screen shot, the `qft_circuit(4)` works, am I missing something?

**Comment by Roger-luo** [comment]
I again double-checked, `qft_circuit` exists. In your second screen shot you have successfully run it. I don't see what's the issue here, I'm closing this. Feel free to open new one if this is still a problem.

In REPL:

```julia
julia> using Yao, YaoExtensions

julia> qft
qft         qft_circuit
julia> qft_circuit(4)
nqubits: 4
chain
├─ chain
│  ├─ put on (1)
│  │  └─ H
│  ├─ control(2)
│  │  └─ (1,) shift(1.5707963267948966)
│  ├─ control(3)
│  │  └─ (1,) shift(0.7853981633974483)
│  └─ control(4)
│     └─ (1,) shift(0.39269908169872414)
├─ chain
│  ├─ put on (2)
│  │  └─ H
│  ├─ control(3)
│  │  └─ (2,) shift(1.5707963267948966)
│  └─ control(4)
│     └─ (2,) shift(0.7853981633974483)
├─ chain
│  ├─ put on (3)
│  │  └─ H
│  └─ control(4)
│     └─ (3,) shift(1.5707963267948966)
└─ chain
   └─ put on (4)
      └─ H
```
