### ISSUE TITLE
Fail to install Yao

### ISSUE THREAD

**Issue by aylive** [QuantumBFS/Yao.jl#273]
Hello, there!
I tried to install Yao in terminal, and here is what it showed, (Julia version 1.5.3)
> (@v1.5) pkg> add Yao
 Installing known registries into `~/.julia`
######################################################################## 100.0%
A/Ansillary/Package.toml: truncated gzip input
tar: Error exit delayed from previous errors.
ERROR: could not download https://pkg.julialang.org/registry/23338594-aafe-5451-b93e-139f81909106/3689ed8a4374242a1dd78df375a68e0486cad1f5

Looking forward to your reply.

**Comment by femtomc** [comment]
That doesn’t seem like a Yao issue. Did you try and install another package to determine if it was Yao or Pkg?

**Comment by aylive** [comment]
> That doesn’t seem like a Yao issue. Did you try and install another package to determine if it was Yao or Pkg?

Thanks, you're right. It's not a Yao issue. But I just still don't know how to solve it.

**Comment by Roger-luo** [comment]
I think this is a PkgServer issue I've pinged @staticfloat on slack. Are you using it from China? Maybe there's something happening for the redirect?

**Comment by ChenZhao44** [comment]
I think it is an issue from the PkgServer. And I solve this it temporarily by changing the mirror of the PkgServer.

```julia
julia> ENV["JULIA_PKG_SERVER"] = "https://mirrors.bfsu.edu.cn/julia"

```

**Comment by Roger-luo** [comment]
I'm closing this since it's not our issue, feel free to open new issues if you have any questions.
