### ISSUE TITLE
webpage (tutorial/documentation/etc.) pipeline improvements

### ISSUE THREAD

**Issue by Roger-luo** [QuantumBFS/Yao.jl#278]
*This issue has been tagged for a bounty during [#unitaryHACK](https://github.com/unitaryfund/unitaryhack/blob/main/participating-projects.md)*

This issue is for tracking the web page related problems

## Layouts

1. we need a more consistent solution to add banners to pages, see also ([Documenter/#1132](https://github.com/JuliaDocs/Documenter.jl/issues/1132))
2. improve large screen experience ([Documenter/#1563](https://github.com/JuliaDocs/Documenter.jl/issues/1563))
3. improve CSS to have a more consistent style.

## Tutorial

1. our Pluto tutorial is included via `<iframe>` which has a delay and bad layout, unlike the previous tutorials based Literate.jl, we don't have an easy to download button at the moment
2. the tutorial page table of content (the left panel) has an inconsistent layout with the banner

## Pipeline

ideally, we should move all documentation into one repo, and build them together, like DiffEq documentation, this requires

1. a CI that gets triggered (or a nightly cron job) for the master branch to rebuild new documentation parts for each component packages
2. integration with the front page

**Comment by Roger-luo** [comment]
@fonsp just show me a solution to insert `iframe` here: https://htmlview.glitch.me/ maybe we can reconsider using `iframe` for the tutorial part now

**Comment by VarLad** [comment]
Try implementing it with the existing tutorials to see how it goes?

**Comment by VarLad** [comment]
If anyone lands on this issue, kindly note that I've undertook this Hack

**Comment by VarLad** [comment]
@Roger-luo Is the work so far good enough for the bounty？If so, it'd be nice if you can tag the related PRs here
