### ISSUE TITLE
cannot install CuYao and YaoExtensions

### ISSUE THREAD

**Issue by HamidArianZad** [QuantumBFS/Yao.jl#326]
Hello,

I tried to run the code: Listing 12: CUDA register, noted in source paper: Quantum 2020-09-29.
I got some errors.
First, I installed Yao and cuda on Julia v1.6.5 then run the code as follows:
1. julia> using CuYao
2. julia> r = ArrayReg(bit"1010") ;
3. julia> r = cu(r) ;
But I get error: syntex: extera token "qubits" after end of expression 

YaoExtensions also does not work for me as well.
![Julia_Error](https://user-images.githubusercontent.com/97589591/149637914-a2b78561-d862-40aa-9ab5-a84f34bc4cd8.png)

How can I solve these problems?

Thanks!

**Comment by GiggleLiu** [comment]
Hi, can you please test if your CUDA works properly? also are you using the latest CuYao? it should be version 0.3.1.

**Comment by HamidArianZad** [comment]
> 

Thank you for your reply.
Please find in attachement the version of CuYao that I have installed.
![Julia_Error](https://user-images.githubusercontent.com/97589591/149638376-bb37cba0-1028-4d14-970a-e2dd4543ba95.png)

**Comment by GiggleLiu** [comment]
It looks like your CUDA does not find the correct binary file.

**Comment by GiggleLiu** [comment]
Also, about YaoExtensions, we are going to retire it gradually. You can use `using Yao.EasyBuild` to access most of the functionalities.

**Comment by HamidArianZad** [comment]
> It looks like your CUDA does not find the correct driver/binary file.

I get the attached error accordingly.
![Julia_Error](https://user-images.githubusercontent.com/97589591/149638503-e071fa8e-b129-4050-a1f9-fee173c98060.png)

**Comment by GiggleLiu** [comment]
Then it is a problem of your CUDA.

First, please make sure you have an Nvidia GPU, and your driver is installed properly. If you are using Linux, you should be careful about the driver you use.

**Comment by HamidArianZad** [comment]
> Then it is a problem of your CUDA.
> 
> First, please make sure you have an Nvidia GPU, and your driver is installed properly. If you are using Linux, you should be more careful about the driver you use. If you are using Mac, you probably do not have a Nvidia GPU.

OK, thank you very much for your help. I use Radeon graphic card.

**Comment by Roger-luo** [comment]
If you wish to use the GPU functionality I think only CUDA is supported, otherwise please just use `Yao` instead of `CuYao`. The rest should be the same. Please feel free to open other issues if you have other problems.
