### ISSUE TITLE
add some old interfaces back for qubits

### ISSUE THREAD

**Issue by Roger-luo** [QuantumBFS/Yao.jl#335]
I think we should keep `nqubits` and `insert_qubits!` instead of removing them, I suspect `nqudits` is very intuitive for most people when they are doing just qubits, these are relatively simple to just forward as `nqubits(x) = nlevels(x)==2 ? nqudits(x) : error("...")` while keep some old code keep working

**Comment by GiggleLiu** [comment]
`nqubits` are kept in the new interface. I also added the `insert_qubits!` in the last commit in this PR: https://github.com/QuantumBFS/Yao.jl/pull/334
