### ISSUE TITLE
Github link on website does not work

### ISSUE THREAD

**Issue by Krastanov** [QuantumBFS/Yao.jl#347]
The github link in the header of the frontpage links back to the frontpage https://yaoquantum.org/#

**Comment by divshacker** [comment]
Just made a PR. Let me know your views 
Thanks

**Comment by divshacker** [comment]
Hey, Your slack link is expired, Can you guys please revoke it. @Roger-luo 
Also this is a bounty Issue of unitaryhack. Please let me know about further steps
Thanks

**Comment by Roger-luo** [comment]
which slack link is expired?

**Comment by divshacker** [comment]
> which slack link is expired?
> 
> > Also this is a bounty Issue of unitaryhack. Please let me know about further steps
> 
> I think that's it, this is a easy simple issue
The slack link is fixed now

**Comment by Roger-luo** [comment]
Closing this then feel free to post other issues.
