### ISSUE TITLE
show case of your own project in Yao's documentation

### ISSUE THREAD

**Issue by Roger-luo** [QuantumBFS/Yao.jl#382]
requirements

- the format should be written as Documenter markdown: https://juliadocs.github.io/Documenter.jl/dev/man/syntax/
- the code blocks should be copy-pastable in Julia REPL

**Comment by radras** [comment]
Hello! I started working on an example and I wanted to ask what is the easiest way to view deployed page? Can I get workflows approved or do I have to build it myself? I made a PR #398

**Comment by Roger-luo** [comment]
Hi @radras thanks for joining the unitary hack! The easiest way to view deploy page is to generate the notebook via [Literate](https://github.com/fredrikekre/Literate.jl), which can generate either a notebook or markdown file (it's not exactly the webpage we build, but close enough)

**Comment by GiggleLiu** [comment]
@JuliaCN 2022hack (setting this issue as a bounty issue of JuliaCN 2022 Hackathon)
