### ISSUE TITLE
update docs for @ket_str

### ISSUE THREAD

**Issue by hros** [QuantumBFS/Yao.jl#389]
the doc for `@ket_str` macro:
```julia
  Create a ket register. See also @bra_str.

  Example
  ≡≡≡≡≡≡≡≡≡

  a symbolic quantum state can be created simply by

  julia> ket"110" + 2ket"111"
  |110⟩ + 2.0|111⟩

  qubits can be partially actived by focus!

  julia> ket"100" + ket"111" |> focus!(1:2)
  ERROR: UndefVarError: focus! not defined
  Stacktrace:
   [1] top-level scope
     @ none:1
```

It seems that `focus!` no longer accepts ranges, only a tuple of indices
The docs for `@ket_str` should be updated accordingly, or reimplement the support for ranges in `focus!`

**Comment by Roger-luo** [comment]
I just checked again the following works, It seems to me that you didn't `using Yao` to get the definition of `focus!` function?

```julia
julia> using Yao, SymEngine

julia> ket"110" + 2ket"111"
|110⟩ + 2.0|111⟩

julia> r = ket"110" + 2ket"111"
|110⟩ + 2.0|111⟩

julia> ket"100" + ket"111" |> focus!(1:2)
|100⟩ + |111⟩
```

**Comment by hros** [comment]
I did use the package with `using Yao`, otherwise I wouldn't have gotten the help message for `@ket_str`

I can confirm that the command accepts ranges, though for some reason the error message in the doc for `@ket_str` is still there

**Comment by Roger-luo** [comment]
Which version are you using?

**Comment by hros** [comment]
The error message in the help os both in the stable and the dev versions

**Comment by Roger-luo** [comment]
can you point out how to reproduce this? I'm not able to reproduce this in any recent versions or on master branch. I just double-checked error message `ERROR: UndefVarError: focus! not defined` doesn't exists anywhere in our documentation, so I'm wondering what's the full stacktrace of this and how did you reproduce this?

**Comment by GiggleLiu** [comment]
I can not reproduce it neither.
