### ISSUE TITLE
is append_qubit! deprecated?

### ISSUE THREAD

**Issue by hros** [QuantumBFS/Yao.jl#390]
the example of [Shor's 9 qubit correction code](https://docs.yaoquantum.org/dev/generated/examples/5.shor-9-code/index.html) has the following line:
```julia
s = α * ket"0" + β * ket"1" |> append_qudits!(8)
```
This results in:
```julia
ERROR: UndefVarError: append_qudits! not defined
```
However, the function is availalbe in the development branch (Yao#master)
Then again, the source code of the stable branch lists the function as deprecated
What is the current state of this function, should we use it or an alternative?

**Comment by Roger-luo** [comment]
the latest dev branch is not released yet, I believe you are looking at the development version of the documentation as well, there are some breaking changes recently which we will later cut a minor release + deprecation warning. 

the old interface was called `addbits!` in the stable doc: https://docs.yaoquantum.org/stable/generated/quick-start/5.shor-9-code/index.html

you can switch different doc version here
<img width="341" alt="Screen Shot 2022-05-16 at 3 18 02 PM" src="https://user-images.githubusercontent.com/8445510/168666150-89463718-c514-4263-9caa-1fcb0e210cf2.png">

**Comment by hros** [comment]
thanks!
