### ISSUE TITLE
YaoExtension incompatible w/ stable Yao version

### ISSUE THREAD

**Issue by fauseweh** [QuantumBFS/Yao.jl#400]
I am using YaoExtension to setup variational circuits but I need features from the currently stable yao version. Right now YaoExtensions at 0.2.5 is compatible only with v0.7.4, and for 0.8 and beyond there is no compatible YaoExtensions version in the julia package manager.

What is the holdup in YaoExtension and what needs to be fixed for it?

**Comment by Roger-luo** [comment]
Hi as mentioned in its README, it's not deprecated in favor of Yao.EasyBuild module as builtin.

**Comment by fauseweh** [comment]
Ahh yes just found it. The syntax of variational_circuit is now a bit different but I found a work around. Thanks!
