### ISSUE TITLE
Incomplete docstring for `measure`: missing custom basis measurement example

### ISSUE THREAD

**Issue by lvignoli** [QuantumBFS/Yao.jl#401]
See https://docs.yaoquantum.org/dev/man/registers.html#YaoAPI.measure in the docs.
The example for measuring in a custom basis is cropped.

The docstring is indeed incomplete:

https://github.com/QuantumBFS/Yao.jl/blob/15eb406feaf40e7eb4f0ffaa956aef0b138917c5/lib/YaoAPI/src/registers.jl#L412-L422

**Comment by GiggleLiu** [comment]
Oh, that is a good catch. Will fix it in the next update.Since this is a document fix, I pushed the commit to the master directly: https://github.com/QuantumBFS/Yao.jl/commit/b8a0cb2c73ab002e89c7a584e5c753a5c7113465

Thank you for the report of document missing!

**Comment by lvignoli** [comment]
Thanks for the quick fix!
