### ISSUE TITLE
[Block] List of gates for realization/performance benchmark

### ISSUE THREAD

**Issue by GiggleLiu** [QuantumBFS/Yao.jl#42]
# A list of gates for performance benchmark
1. simple gates: Gs

	* X(5)
	* H(5)
	* Rx(5)
	* U2(5, 6)
2. control gates, for g in Gs

	* C(3) g
	* C(1) C(2) NC(3) X(5)
3. multiple gates

	* X(1) X(2) X(3) X(4)
	* H(1) H(2) H(3) H(4)
	* X(3) Y(4) Z(5) [C(1) Z(6)]
	* X(3) Rx(4) Y(5)
4. Grover Block

	* 2|psi><psi|-1
5. TimeEvolution

	* Exp(-iHt)

## Data Representations
* X, Y on single qubit/multiple qubits -> PermuteMultiply
* Z on single qubit/multiple qubits -> Diagonal
* H on single qubit -> SparseMatrixCSC
* single and multiple Control on gate G -> typeof(G), push  performance for CNOT, CZ gates.
* TimeEvolution, use `expmv`.

**Comment by Roger-luo** [comment]
Have you updated this in benchmark? What do we have in benchmark?

**Comment by Roger-luo** [comment]
This is already done, closed in duplicate with #122
