### ISSUE TITLE
Retrieving a Unitary from a circuit

### ISSUE THREAD

**Issue by BoltzmannEntropy** [QuantumBFS/Yao.jl#429]
Dear team,
Is that possible? If yes, how? I wasn't able to find anything like that in the documentation.

Thanks,

**Comment by GiggleLiu** [comment]
If you are mentioning about manipulating the circuit structure, maybe you will find the **
Manipulate the block tree** section of this notebook be useful: https://giggleliu.github.io/notebooks/notebooks/yaoblocks.html

The `subblocks` API might be the one most relevant. If you want the matrix representation of a unitary, just call `mat`.
