### ISSUE TITLE
9 qubit performance benchmark

### ISSUE THREAD

**Issue by GiggleLiu** [QuantumBFS/Yao.jl#43]
Using Bars-and-Stripes 3x3 depth = 10 circuit,

|     |ProjectQ performance | Scipy Performance| Julia |
| ---- | ----------------------------- | ------------ | --------- |
| initial run | 0.28s | 0.5s | ? |
| cached run | ?  | 0.00175 | ? |

**Comment by GiggleLiu** [comment]
why do you close it"

**Comment by Roger-luo** [comment]
We had this benchmark somewhere. I will add this in #144. Close in dup of this PR.

**Comment by Roger-luo** [comment]
I think we have this in the slides now for 4-15 qubits, I'll put the benchmark in the documentation later.
