### ISSUE TITLE
Kron and chain

### ISSUE THREAD

**Issue by BoltzmannEntropy** [QuantumBFS/Yao.jl#430]
I am having trouble understating the way the 'chain' command works. 
<img width="762" alt="image" src="https://user-images.githubusercontent.com/91342039/196028574-319d2394-29e8-4330-a79f-0f1215925427.png">

Mathematically, this should have represented: `(I  ⊗ Y  ⊗ I  ⊗ I) (Y  ⊗ I  ⊗ I  ⊗ H) (X  ⊗ H  ⊗ H  ⊗ H)`  but what i get is that the third row, is mingled into the second row. 
```
circuit = chain(
    4,    
    chain(put(1=>X),repeat(H, 2:4)), #1
    chain(put(1=>Y),put(2=>igate(1)),put(3=>igate(1)),put(4=>H)), #2   
    chain(put(1=>igate(1)),put(2=>Y),put(3=>igate(1)),put(4=>igate(1))), #3        
)

```

**Comment by GiggleLiu** [comment]
Thanks for the issue, it is a matter of visualization, `(I ⊗ Y ⊗ I ⊗ I) (Y ⊗ I ⊗ I ⊗ H) (X ⊗ H ⊗ H ⊗ H)` is equivalent to `(Y ⊗ Y ⊗ I ⊗ H) (X ⊗ H ⊗ H ⊗ H)`. In `YaoPlots`, the default rule for visualization is:

1. if you apply an `igate` on a line, it does not take any slot, and
2. a gate moves to the first unoccupied slot in a row.

**Comment by BoltzmannEntropy** [comment]
Thanks for the prompt reply/ 
I already tried with a Kron command, even your example above (method 2) is not plotted correctly. the Y gate should be on a new slot. 
<img width="476" alt="image" src="https://user-images.githubusercontent.com/91342039/196034565-20d8c5c1-a525-44af-ba37-b922e6054db4.png">

**Comment by GiggleLiu** [comment]
All of them are correct. It is a matter of display. The number of slots in the plot is not equivalent to the number of blocks in the chain.

**Comment by BoltzmannEntropy** [comment]
Yes, I understand that, but if I am trying to reproduce Figures from nielsen & chung I am never going to get the same plot while if i use qiskit/cirq I get the exact same plot.

**Comment by GiggleLiu** [comment]
One option is to add a `barrier` block to the circuit to help visualization.

**Comment by BoltzmannEntropy** [comment]
Many thanks for your suggestion, 
I wonder how no one has asked this before, for larger circuits involving many Krons and gates, it would be almost impossible to visually verify a gate without the plots being correctly displayed.

**Comment by GiggleLiu** [comment]
Hmm, what you said makes sense. Maybe we should add a global variable to toggle the display mode.

**Comment by BoltzmannEntropy** [comment]
An example in cirq:
<img width="721" alt="image" src="https://user-images.githubusercontent.com/91342039/196035667-dc79f28a-9984-486c-addb-d61cd9c0c94e.png">

**Comment by GiggleLiu** [comment]
Thanks for the example. I added a new global variable in the PR: https://github.com/QuantumBFS/YaoPlots.jl/pull/60 to toggle the barrier mode and compact mode.

The reason why we use compact mode by default is, it do make some circuits more suitible for publication purpose.
Please find an example in the comment of that PR.

**Comment by BoltzmannEntropy** [comment]
<img width="776" alt="image" src="https://user-images.githubusercontent.com/91342039/196118856-ddfdc6d3-e174-47f1-8abe-2d232a0732ce.png">
