### ISSUE TITLE
Implementing circuit.append(cirq.X(qubits[3]).controlled_by(qubits[1],qubits[4]))

### ISSUE THREAD

**Issue by BoltzmannEntropy** [QuantumBFS/Yao.jl#431]
Hello, 
Is that supported in Yao? 

<img width="55" alt="image" src="https://user-images.githubusercontent.com/91342039/196119416-caaccc87-1f06-44ee-9872-a7fa026c95dd.png">

**Comment by GiggleLiu** [comment]
Thanks for the issue. Yes, it is
```julia
control(4, (1, 4), 3=>X)
```

While it is a good question and is welcomed aks here, to make the answer more accessible to other users, a better place to ask question is discourse: https://discourse.julialang.org/c/domain/quantum/52
