### ISSUE TITLE
Extending Blocks to include timing information of a quantum gate

### ISSUE THREAD

**Issue by exAClior** [QuantumBFS/Yao.jl#434]
### Enhancement Idea
In #426, enhancement of `Block` on the account of revealing circuit depth is requested. On a related topic, it might be rewarding to also add the information of gate time into `Block` as well.  

### Motivation
On real machines, `XGate` and `CXGate` will have drastically different duration. `Block` representation ignores such difference.  With `Block` representation, an `XGate` applied on qubit 1 and `CXGate` applied on qubit 2,3 will make it look like all three qubits experienced some sort of control for the same amount of time. But in fact, qubit 1 will remain idle for a long time. 

Error mitigation techniques like [Dynamical Decoupling](https://youtu.be/67jRWQuW3Fk) requires inserting random gates on idle qubits. `Block`s with timing information could help

1. Give better visualization which qubits are idle.
2. Make it easier to pack `Blocks` in a Tetris style. Then, insertion location of random gates could perhaps be found more easily.

In #253 there seems to be the inclination towards giving the user real quantum machine usage. Might as well make things more native towards hardware. 

### Concerns

Might be too much of a complication on the simple and elegant `Block` implementation.  Not many folks would really need this feature for now.  This is more like the [pulse-level ](https://qiskit.org/documentation/stable/0.33/apidoc/pulse.html) quantum circuit in Qiskit. 

If you think this is a good enhancement, I would be glad to help with the implementation or the related issue #426.

**Comment by GiggleLiu** [comment]
FYI, the next Yao community call is Thursday 12AM (today, midnight).

**Comment by exAClior** [comment]
@Roger-luo  My apologies! I was not able to join the community call due to traveling and relocating. Thank you for the comprehensive response regarding my proposal! I also talked to @GiggleLiu about this issue after the community call happened. Seems like my concern was true. My proposal conflicts with the philosophy of Yao. So the next move should be done with more care. I think I will close this issue for now. Should time permit, I think more conversation on the compilation pipeline etc should be done before I do / propose anything.
