### ISSUE TITLE
label not found

### ISSUE THREAD

**Issue by erlebach** [QuantumBFS/Yao.jl#438]
I am running the tutorial `5-more-gate` in Pluto.jl, and am getting an error on the following cell: 
```
let
	S_Gate = chain(1, put(1 => label(shift(π/2), "S"))) #The S gate
	plot(S_Gate)
end
```
UndefVarError: label not defined

    top-level scope@[Local: 2](http://localhost:1234/edit?id=82eb9892-58a1-11ed-05a7-5133c803f9c8#)
```
I could of course remove the `label`. However, I expect other tutorials to break. Has `label` been removed? I searched the source code for Yao.jl and did not find reference to `label`.  Perhaps reference to `label` should  be removed from the tutorials? Thanks!

**Comment by GiggleLiu** [comment]
It is another outdated tutorial, the function name has been changed to “addlabel”, sorry for that.
https://github.com/QuantumBFS/YaoPlots.jl/blob/0157a3e8d57113d6219a8dba9d2f320f99fc1395/src/helperblock.jl#L34
