### ISSUE TITLE
Python Interface

### ISSUE THREAD

**Issue by yangguohao** [QuantumBFS/Yao.jl#465]
Hi there, I have come across the Yao library and noticed that it has a Python interface available https://github.com/QuantumBFS/yao-python. I was wondering if this Python package is currently functional and being actively maintained? Additionally, could you provide an example for how this package can be used? Thank you.

**Comment by Roger-luo** [comment]
> I was wondering if this Python package is currently functional and being actively maintained?

no, it was only an experimental project. And should be rewritten using PythonCall now. 
You can call any Julia packages through https://cjdoris.github.io/PythonCall.jl/stable/juliacall/

**Comment by yangguohao** [comment]
Cool, I will take a look at it. Thanks for replying.
