### ISSUE TITLE
QRNG

### ISSUE THREAD

**Issue by BoltzmannEntropy** [QuantumBFS/Yao.jl#473]
Hello, 
My goal here is to create a Quantum Generative Adversarial Network (QGAN). A critical component of this endeavor is the ability to sample from a normal distribution. However, given the constraints of the (Hadamard based) available quantum random number generator, which only produces 1 and -1, there's a necessity to create continuous random numbers between -1 and 1 (or 0 and 1).

The question at hand is whether it's feasible to train and optimize a Parametrized Quantum Circuit (PQC) to generate a Gaussian distribution with a zero mean. If this is possible, the corresponding code would be very beneficial. 

Thanks,

**Comment by GiggleLiu** [comment]
Wondering if the quantum circuit born machine is what you need.
https://docs.yaoquantum.org/dev/generated/examples/6.quantum-circuit-born-machine/index.html

Also, you might be interested in this quantum GAN implementation in QuAlgorithmZoo
https://github.com/QuantumBFS/QuAlgorithmZoo.jl/tree/master/examples/QuGAN
