### ISSUE TITLE
New blocks to support in v0.3

### ISSUE THREAD

**Issue by GiggleLiu** [QuantumBFS/Yao.jl#59]
* `roll(position::Vector{Int}, gates::Vector{Gate})`, roller with gates on specific positions.
* `MatBlock{N, T}(matrix::Matrix)`, used in phase estimation.
* `FuncBlock{N, T}(func::Function)`, to fit the `MatBlock`.
* `IBlock{N, T}`, the gate of doing nothing.
* `apply!(reg, block::ControlBlock{MatBlock})`, apply register on controlled large block directly.

**Comment by Roger-luo** [comment]
We should reconsider this, some is duplicate with the other. and `Roller` maybe deleted or move out of the main repo to `YaoStdExt`
